name: numbers_to_text
description: convert numbers into their textual representation in both Arabic and English.
version: 0.1.0
repository: https://github.com/masreplay/number_to_text

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  intl: ^0.17.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
