name: number_to_text
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  intl: ^0.17.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
